# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


RANK_CHANGES = [
    ('2nd Officer / Bosun',
        'Deck - All', '2nd Officer'),
    ('3rd Officer/Bosun',
        'Deck - All', '3rd Officer'),
    ('Ordinary Seaman',
        'Deck - All', 'AB'),
    ('Coxswain',
        'Deck - All', 'Bosun'),
    ('Deckhand / Carpenter',
        'Deck - All', 'Carpenter'),
    ('Chief Security Officer',
        'Deck - All', 'Security Officer'),
    ('Deck/Stew',
        'Deck - All', 'Deckhand'),
    ('Senior Deckhand',
        'Deck - All', 'Deckhand'),
    ('Deckhand / 1st Mate',
        'Deck - All', 'Deckhand'),
    ('Diving Instructor',
        'Deck - All', 'Deckhand'),
    ('Deckhand/Dive Instructor',
        'Deck - All', 'Deckhand'),
    ('Lead Deckhand',
        'Deck - All', 'Deckhand'),
    ('Captain',
        'Deck - All', 'Master'),
    ('Ships Physician',
        'Deck - All', 'Doctor'),
    ('Fleet Superintendent',
        'Deck - All', 'Superintendent'),
    ('Fleet Manager',
        'Deck - All', 'Manager'),
    ('Marine Risk Manager',
        'Deck - All', 'Manager'),
    ('Vessel Manager',
        'Deck - All', 'Manager'),
    ('Technical Marine Manager',
        'Deck - All', 'Manager'),
    ('ISM/ISPS Manager',
        'Deck - All', 'Manager'),
    ('Berthing Master',
        'Deck - All', 'Harbour Master'),
    ('Ice Pilot',
        'Deck - All', 'Pilot'),
    ('Safety and Environmental Officer',
        'Deck - All', 'Safety Officer'),
    ('Ship Manager',
        'Deck - All', 'Manager'),
    ('Day Systems Engineer',
        'Engine - All', 'Engineer'),
    ('Hotel Engineer',
        'Engine - All', 'Engineer'),
    ('Ships Service Engineer',
        'Engine - All', 'Engineer'),
    ('Assistant engineer',
        'Engine - All', 'Engineer'),
    ('Sole Engineer',
        'Engine - All', 'Engineer'),
    ('Electrical Superintendent',
        'Engine - All', 'Superintendent'),
    ('Environmental Engineer',
        'Engine - All', 'Environmental Officer'),
    ('Repairman/Pipe Fitter',
        'Engine - All', 'Fitter'),
    ('Tender Mechanic',
        'Engine - All', 'Mechanic'),
    ('Data Systems Manager',
        'Technical / Specialist - All', 'AV/IT Officer'),
    ('IT Manager',
        'Technical / Specialist - All', 'AV/IT Officer'),
    ('IT Officer',
        'Technical / Specialist - All', 'AV/IT Officer'),
    ('Assistant Data Systems Manager',
        'Technical / Specialist - All', 'AV/IT Officer'),
    ('Chief Electrical Engineer',
        'Technical / Specialist - All', 'Chief Electrician'),
    ('1st Electrician',
        'Technical / Specialist - All', 'Chief Electrician'),
    ('Electronic Engineer',
        'Technical / Specialist - All', 'Electrician'),
    ('2nd ETO',
        'Technical / Specialist - All', 'ETO'),
    ('Lift Technician',
        'Technical / Specialist - All', 'Technician'),
    ('Maintenance Manager',
        'Technical / Specialist - All', 'Manager'),
    ('Technical Manager',
        'Technical / Specialist - All', 'Manager'),
    ('Facility Manger',
        'Technical / Specialist - All', 'Manager'),
    ('Executive chef',
        'Hotel', 'Executive Chef de Cuisine'),
    ('Chef De Cuisine Colonnade',
        'Hotel', 'Chef de Cuisine'),
    ('2nd executive chef',
        'Hotel', 'Chef de Cuisine'),
    ('Guest Chef',
        'Hotel', 'Chef de Cuisine'),
    ('Chef (yacht)',
        'Hotel', 'Sous chef'),
    ('2nd Chef',
        'Hotel', 'Sous chef'),
    ('Sous/Crew Chef',
        'Hotel', 'Sous chef'),
    ('3rd Chef',
        'Hotel', 'Chef de Partie'),
    ('Crew Chef',
        'Hotel', 'Chef de Partie'),
    ('Pastry chef',
        'Hotel', 'Chef De Partie - Pastry'),
    ('Demi Chef de Partie - Pastry',
        'Hotel', 'Demi Chef de Partie'),
    ('Assistant Chef de Partie',
        'Hotel', 'Demi Chef de Partie'),
    ('Cook (Yacht)',
        'Hotel', 'Commis Chef'),
    ('Corporate Baker',
        'Hotel', 'Baker'),
    ('Head Baker',
        'Hotel', 'Baker'),
    ('Chief Galley Steward (Cruise)',
        'Hotel', 'Sanitation Officer'),
    ("Maitre D'",
        'Hotel', 'Restaurant Manager'),
    ('Lido Manager',
        'Hotel', 'Restaurant Manager'),
    ('F&B Manager',
        'Hotel', 'Food and Beverage Manager'),
    ('Assistant food & beverage manager',
        'Hotel', 'Food and Beverage Manager'),
    ('Fleet Dining and Beverage Manager',
        'Hotel', 'Food and Beverage Manager'),
    ('Corp. Restaurant & Bar Manager',
        'Hotel', 'Food and Beverage Manager'),
    ('Junior Food & Beverage Supervisor',
        'Hotel', 'Food and Beverage Supervisor'),
    ('Chef de Rang',
        'Hotel', 'Restaurant Waiter'),
    ('Waiter',
        'Hotel', 'Restaurant Waiter'),
    ('Waitress',
        'Hotel', 'Restaurant Waiter'),
    ('Head Waiter',
        'Hotel', 'Restaurant Waiter'),
    ('Head Waitress',
        'Hotel', 'Restaurant Waiter'),
    ('Public Rooms Manager',
        'Hotel', 'Bar Manager'),
    ('Hotel Lounge General Manager',
        'Hotel', 'Bar Manager'),
    ('Barman',
        'Hotel', 'Bartender'),
    ('Cocktail Bar Tender',
        'Hotel', 'Bartender'),
    ('Head Bartender ',
        'Hotel', 'Bartender'),
    ('Assistant Bar Waiter',
        'Hotel', 'Bar Waiter'),
    ('Assistant Sommelier',
        'Hotel', 'Sommelier'),
    ('Wine waiter',
        'Hotel', 'Sommelier'),
    ('Cellar Master',
        'Hotel', 'Sommelier'),
    ('Head Sommelier',
        'Hotel', 'Sommelier'),
    ('Hotel manager',
        'Hotel', 'Hotel Director'),
    ('Assistant Hotel Director',
        'Hotel', 'Hotel Director'),
    ('General Manager/Hotel Director',
        'Hotel', 'General Manager'),
    ('House Manager',
        'Hotel', 'General Manager'),
    ('Chief Financial Accountant',
        'Hotel', 'Chief Purser'),
    ('Purser/PA',
        'Hotel', 'Purser'),
    ('Second Purser',
        'Hotel', 'Purser'),
    ('Crew Officer',
        'Hotel', 'Crew Purser'),
    ('Communications Purser',
        'Hotel', 'Assistant Purser'),
    ('Clearance Officer',
        'Hotel', 'Assistant Purser'),
    ('Paymaster',
        'Hotel', 'Assistant Purser'),
    ('Desktop Publisher',
        'Hotel', 'Assistant Purser'),
    ('Guest relations manager',
        'Hotel', 'Guest Services Manager'),
    ('Guest Programme Manager',
        'Hotel', 'Guest Services Manager'),
    ('Reception Manager',
        'Hotel', 'Front Office Manager'),
    ('Front desk supervisor',
        'Hotel', 'Front Office Supervisor'),
    ('Room Service Supervisor',
        'Hotel', 'Front Office Supervisor'),
    ('Host/Hostess Couple',
        'Hotel', 'Host'),
    ('International Host/ess',
        'Hotel', 'Host'),
    ('Personnel & Training Manager',
        'Hotel', 'Personnel & Training Manager'),
    ('Human resources officer',
        'Hotel', 'HR Advisor'),
    ('Assistant Provision Master',
        'Hotel', 'Provision Master'),
    ('Lead Storekeeper',
        'Hotel', 'Provision Master'),
    ('Storekeeper',
        'Hotel', 'Provision Master'),
    ('Controller',
        'Hotel', 'Hotel Controller'),
    ('Hotel Finance Controller',
        'Hotel', 'Hotel Controller'),
    ('Inventory Manager',
        'Hotel', 'Hotel Controller'),
    ('Night Receptionist',
        'Hotel', 'Night Porter'),
    ('Chief Housekeeper',
        'Hotel', 'Executive Housekeeper'),
    ('Head Housekeeper',
        'Hotel', 'Executive Housekeeper'),
    ('Housekeeper (Florist)',
        'Hotel', 'Housekeeper'),
    ('Housekeeper/Nurse',
        'Hotel', 'Housekeeper'),
    ('Senior Housekeeper',
        'Hotel', 'Housekeeper'),
    ('Second Housekeeper',
        'Hotel', 'Assistant Housekeeper'),
    ('Rooms Assistant Manager',
        'Hotel', 'Assistant Housekeeper'),
    ('Junior Housekeeper',
        'Hotel', 'Assistant Housekeeper'),
    ('Head Steward/ess (yacht)',
        'Hotel', 'Chief Steward/ess (Yacht)'),
    ('Head Service Stewardess',
        'Hotel', 'Chief Steward/ess (Yacht)'),
    ('Head of Service (Female)',
        'Hotel', 'Chief Steward/ess (Yacht)'),
    ('Head of Service',
        'Hotel', 'Chief Steward/ess (Yacht)'),
    ('Lead Service Stew',
        'Hotel', 'Chief Steward/ess (Yacht)'),
    ('Stewardess',
        'Hotel', 'Housekeeping Stewardess'),
    ('Cabin steward/ess',
        'Hotel', 'Housekeeping Stewardess'),
    ('Steward',
        'Hotel', 'Steward/ess'),
    ('Stewardess/Cook',
        'Hotel', 'Steward/ess'),
    ('Stewardess / Bartender',
        'Hotel', 'Steward/ess'),
    ('Stew/deckhand',
        'Hotel', 'Steward/ess'),
    ('Steward',
        'Hotel', 'Steward/ess'),
    ('Stewardess / Masseuse',
        'Hotel', 'Steward/ess'),
    ('Chief Steward',
        'Hotel', 'Steward/ess'),
    ('Junior Stewardess',
        'Hotel', 'Steward/ess'),
    ('Second Stewardess',
        'Hotel', 'Steward/ess'),
    ('Service Steward/ess / Housekeeper',
        'Hotel', 'Steward/ess'),
    ('Steward / Bartender',
        'Hotel', 'Steward/ess'),
    ('Chef / Stewardess',
        'Hotel', 'Steward/ess'),
    ('Service Stewardess',
        'Hotel', 'Steward/ess'),
    ('Assistant Interior Manager',
        'Hotel', 'Interior Manager'),
    ('Activities Staff',
        'Hotel', 'Cruise Staff'),
    ('Assistant Yacht Manager',
        'Hotel', 'Assistant Manager'),
    ('Destinations Manager',
        'Hotel', 'Shore Ex Manager'),
    ('Destinations Staff',
        'Hotel', 'Shore Ex Manager'),
    ('Destination Service Assistant',
        'Hotel', 'Shore Ex Assistant'),
    ('Beautician',
        'Hotel', 'Beauty Therapist'),
    ('Beautician-Masseuse/Housekeeper',
        'Hotel', 'Beauty Therapist'),
    ('Spa Therapist',
        'Hotel', 'Beauty Therapist'),
    ('Spa Receptionist',
        'Hotel', 'Beauty Therapist'),
    ('Masseuse',
        'Hotel', 'Beauty Therapist'),
    ('Spa Front of House Manager',
        'Hotel', 'Spa Manager'),
    ('Jeweler',
        'Hotel', 'Shop Assistant'),
    ('Yoga/Fitness Instructor',
        'Hotel', 'Fitness Instructor'),
    ('Botanist / Zodiac Driver',
        'Hotel', 'Expedition Leader'),
    ('Laundry Steward/ess',
        'Hotel', 'Laundryman'),
    ('Laundry Girl',
        'Hotel', 'Laundryman'),
    ('Sport Director',
        'Hotel', 'Sports Co-ordinator'),
    ('Sports Couple',
        'Hotel', 'Sports Co-ordinator'),
    ('Crewing Manager',
        'Hotel', 'Manager'),
    ('Land Operation Manager',
        'Hotel', 'Manager'),
    ('Marine and Technical Operations Manager',
        'Hotel', 'Manager'),
    ('Manager Nautical Operations',
        'Hotel', 'Manager'),
    ('Revenue Manager',
        'Hotel', 'Manager'),
    ('Marine Crew Manager',
        'Hotel', 'Manager'),
    ('Marine Crew Manager',
        'Hotel', 'Manager'),
    ('Marine Economist',
        'Hotel', 'Manager'),
    ('Yacht Manager',
        'Hotel', 'Manager'),
    ('Yacht Manager',
        'Hotel', 'Manager'),
    ('Manager Occupational Safety Programs',
        'Hotel', 'Manager'),
    ('Service Manager',
        'Hotel', 'Manager'),
    ('Operations Manager',
        'Hotel', 'Manager'),
    ('Onboard Revenue Manager',
        'Hotel', 'Manager'),
    ('Property Service Manager',
        'Hotel', 'Manager'),
    ('Director of Sales',
        'Hotel', 'Director'),
    ('Director of Hotel Revenue',
        'Hotel', 'Director'),
    ('Head of Business Development - Marine',
        'Hotel', 'Director'),
    ('Head of Sea Training',
        'Hotel', 'Director'),
    ('Account Manager',
        'Hotel', 'Director'),
    ('Operations Director',
        'Hotel', 'Director'),
    ('South Asian Events Sales Coordinator',
        'Hotel', 'Coordinator'),
    ('Planning Executive',
        'Hotel', 'Executive'),
    ('Marine Recruitment Consultant (Deck and Engine)',
        'Hotel', 'Marine Recruitment Consultant'),
    ('Recruitment Consultant',
        'Hotel', 'Marine Recruitment Consultant'),
    ('Vice President of Hotel Marine Operations',
        'Hotel', 'Vice President'),
    ('Senior Vice President - Hospitality ',
        'Hotel', 'Vice President'),
    ('Senior Vice President - Marine Divison',
        'Hotel', 'Vice President'),
    ('VP of Hotel Operations',
        'Hotel', 'Vice President'),
    ('Catering Superintendent',
        'Hotel', 'Superintendent'),
]


def alter_ranks(apps, schema_editor):
    Rank = apps.get_model('jobs', 'Rank')
    RankGroup = apps.get_model('jobs', 'RankGroup')

    rank_groups = {x.name: x for x in RankGroup.objects.all()}

    for old_name, new_group, new_name in RANK_CHANGES:
        # Find the existing ranks
        old_ranks = Rank.objects.select_related('rank_group').filter(name=old_name)

        for old_rank in old_ranks:
            # Alter the group/name accordingly
            old_rank.rank_group = rank_groups[new_group]
            old_rank.name = new_name
            old_rank.save()


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial_2'),
    ]

    operations = [
        migrations.RunPython(alter_ranks, lambda apps, schema_editor: None),
    ]
